In [1]:
# Basics and Plotting
import pandas as pd
import numpy as np
import scipy as scp
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
import seaborn as sns
from itertools import chain, combinations
import csv

# Sklearn Models
import sklearn.linear_model as skl_lm
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.linear_model import Lasso, Ridge
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split, LeaveOneOut, KFold, cross_val_score, cross_validate
from sklearn.preprocessing import PolynomialFeatures
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier
from sklearn.preprocessing import scale
from sklearn.decomposition import PCA
from sklearn.cross_decomposition import PLSRegression

# Alternative models
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.formula.api as smf

In [2]:
dataset = pd.read_csv("https://raw.githubusercontent.com/jprichmond20/2020ElectionStudy/main/anes_timeseries_2020_csv_20220210.csv")

C:\Users\JP\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (15,17,18,19,21,22,23,25,26,27,29,30,31,33,34,35,37,38,1508,1509) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [3]:
for skip_blank_lines in [True, False]:
    print("Skip Blank Lines:", skip_blank_lines)
    df = pd.read_csv("https://raw.githubusercontent.com/jprichmond20/2020ElectionStudy/main/anes_timeseries_2020_csv_20220210.csv", skip_blank_lines=skip_blank_lines)

    print("Row count:", len(df))
    

Skip Blank Lines: True
Row count: 8280
Skip Blank Lines: False
Row count: 8280


In [ ]:
print("Unique values:", df[df.columns[0]].unique(), "\n")

In [ ]:
df.columns

In [ ]:
df

In [ ]:
df.head()

In [4]:
df = df[["V201004", "V201005", "V201008", 
                    "V201024", "V202110x", "V201030", "V201651", 
                    "V201645", "V201628", "V201627", "V201626", 
                    "V201622", "V201620", "V201607", "V201606", 
                    "V201602", "V201600", "V201601", "V201594", 
                    "V201589", "V201575", "V201565x", "V201550", 
                    "V201549x", "V201540", "V201531", 
                    "V201530y", "V201515", "V201511x", "V201508", 
                    "V201507x", "V201462", "V201453", "V201435", 
                    "V201433", "V201432x", "V201426x", "V201417", 
                    "V201416", "V201411x", "V201393", "V201379", 
                    "V201377", "V201366", "V201364", "V201359x", 
                    "V201335", "V201244", "V201242", "V201241", 
                    "V201240", "V201239", "V201237", "V201231x", 
                    "V201232", "V201220", "V201216", "V201156", 
                    "V201157", "V201122", "V201123", "V201121", 
                    "V201114", "V201100", "V201103", "V201036", 
                   "V201018"]]

In [5]:
df.head()

V201004  V201005  V201008  V201024  V202110x  V201030  V201651  V201645  \
0       -1        2        1       -1        -1       -1        1        3   
1       -1        4        1       -1         3       -1        3        4   
2       -1        1        1       -1         1       -1        3        1   
3       -1        2        1       -1         1       -1        1        1   
4       -1        2        1       -1         2       -1        2        1   

   V201628  V201627  ...  V201156  V201157  V201122  V201123  V201121  \
0        3        1  ...        0       85        5        1        1   
1        0        2  ...        0       50        3        3        1   
2        0        3  ...       60        0        5        5        1   
3        0        4  ...       50       70        4        4        2   
4        0        4  ...       20       70        3        3        4   

   V201114  V201100  V201103  V201036  V201018  
0        1        1        2       -1        2  
1        2        2        5       -1        4  
2        2        1        1       -1       -1  
3        2        2        1       -1        2  
4        2        1        2       -1        4  

[5 rows x 67 columns]

In [ ]:
df

In [ ]:
df.rename(columns = {V2012004:})

In [ ]:
fig, ax = plt.subplots()
colors = {'-9':'blue', '-8':'red', '-1':'green', '1':'blue', '2':'red', '4':'red', '5':'blue'}
grouped = df.groupby('V201018')
for key, group in grouped:
    group.plot(ax=ax, kind='scatter', x='V201156', 
               y='V201157', label=key, color=colors[key])
plt.show()

In [ ]:
plt.figure(dpi=150)
parties = ['D', 'R']
colors = {'-9':'blue', '-8':'red', '-1':'green', '1':'blue', '2':'red', '4':'red', '5':'blue'}
plt.scatter(df['V201156'], df['V201157'], c=df['V201231x'])

plt.xlim(0,100)
plt.ylim(0,100)
plt.legend(df['V201231x'].values)
plt.show()

In [ ]:
mod = smf.ols(formula='V202110x ~ 1 + V201004 + V201005 + V201008 + V201024 + V201030 + V201651 + V201645+ V201628+ V201627+ V201626+ V201622+ V201620+ V201607+ V201606+ V201602+ V201600+ V201601+ V201594+ V201589+ V201575+ V201565x+ V201550+ V201549x+ V201540+ V201531+ V201530y+ V201515+ V201511x+ V201508+ V201507x+ V201462+ V201453+ V201435+ V201433+ V201432x+ V201426x+ V201417+ V201416+ V201411x+ V201393+ V201379+ V201377+ V201366+ V201364+ V201359x+ V201335+ V201244+ V201242+ V201241+ V201240+ V201239+ V201237+ V201231x+ V201232+ V201220+ V201216+ V201156+ V201157+ V201122+ V201123+ V201121+ V201114+ V201100+ V201103+ V201036+ V201018', data=df)

In [ ]:
res = mod.fit()
res.summary()

In [ ]:
vif = pd.DataFrame()
vif['X'] = df.columns
vif['vif'] = [variance_inflation_factor(df.values, i) for i in range(len(df.columns))]
vif

In [ ]:
df['V202110x'].value_counts()

In [ ]:
df.columns.get_loc('V202110x')

In [5]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [6]:
metric_store

[[[0],
  [1],
  [2],
  [3],
  [5],
  [6],
  [7],
  [8],
  [9],
  [10],
  [11],
  [12],
  [13],
  [14],
  [15],
  [16],
  [17],
  [18],
  [19],
  [20],
  [21],
  [22],
  [23],
  [24],
  [25],
  [26],
  [27],
  [28],
  [29],
  [30],
  [31],
  [32],
  [33],
  [34],
  [35],
  [36],
  [37],
  [38],
  [39],
  [40],
  [41],
  [42],
  [43],
  [44],
  [45],
  [46],
  [47],
  [48],
  [49],
  [50],
  [51],
  [52],
  [53],
  [54],
  [55],
  [56],
  [57],
  [58],
  [59],
  [60],
  [61],
  [62],
  [63],
  [64],
  [65],
  [66]],
 [30675.166677422843,
  30513.337803510072,
  30315.31537917019,
  30676.560624169862,
  30640.14123294474,
  30680.816835758465,
  30638.915810908566,
  30644.071851847642,
  30623.585338827663,
  30582.38664885875,
  30660.99691743487,
  30671.304655574877,
  30673.743682230965,
  30637.08241606979,
  30677.37263011222,
  30657.72495178974,
  30602.966706206545,
  30582.31998538485,
  30681.796560341198,
  30678.412077460547,
  30663.677136446302,
  30673.743682230965,
  30

In [7]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([64], 29977.72354016121)

In [8]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,65,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [9]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([63], 29660.635885916097)

In [10]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,65,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64,63] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [11]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([49], 29453.165778767685)

In [12]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,50,51,52,53,54,55,56,57,58,59,60,61,62,65,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64,63,49] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [13]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([2], 29391.419186912033)

In [14]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,50,51,52,53,54,55,56,57,58,59,60,61,62,65,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64,63,49,2] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [15]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([17], 29340.951295232415)

In [16]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,3,5,6,7,8,9,10,11,12,13,14,15,16,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,50,51,52,53,54,55,56,57,58,59,60,61,62,65,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64,63,49,2,17] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [17]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([56], 29312.536830555517)

In [18]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,3,5,6,7,8,9,10,11,12,13,14,15,16,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,50,51,52,53,54,55,57,58,59,60,61,62,65,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64,63,49,2,17,56] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [19]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([38], 29289.339307361428)

In [20]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,3,5,6,7,8,9,10,11,12,13,14,15,16,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,39,40,41,42,43,44,45,46,47,48,50,51,52,53,54,55,57,58,59,60,61,62,65,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64,63,49,2,17,56,38] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [21]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([42], 29268.939720697344)

In [22]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,3,5,6,7,8,9,10,11,12,13,14,15,16,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,39,40,41,43,44,45,46,47,48,50,51,52,53,54,55,57,58,59,60,61,62,65,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64,63,49,2,17,56,38,42] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [23]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([28], 29252.531417339847)

In [24]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,3,5,6,7,8,9,10,11,12,13,14,15,16,18,19,20,21,22,23,24,25,26,27,29,30,31,32,33,34,35,36,37,39,40,41,43,44,45,46,47,48,50,51,52,53,54,55,57,58,59,60,61,62,65,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64,63,49,2,17,56,38,42,28] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [25]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([50], 29243.586672543694)

In [26]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,3,5,6,7,8,9,10,11,12,13,14,15,16,18,19,20,21,22,23,24,25,26,27,29,30,31,32,33,34,35,36,37,39,40,41,43,44,45,46,47,48,51,52,53,54,55,57,58,59,60,61,62,65,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64,63,49,2,17,56,38,42,28,50] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [27]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([15], 29234.24461198143)

In [28]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,3,5,6,7,8,9,10,11,12,13,14,16,18,19,20,21,22,23,24,25,26,27,29,30,31,32,33,34,35,36,37,39,40,41,43,44,45,46,47,48,51,52,53,54,55,57,58,59,60,61,62,65,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64,63,49,2,17,56,38,42,28,50,15] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [29]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([9], 29226.617726163382)

In [30]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,3,5,6,7,8,10,11,12,13,14,16,18,19,20,21,22,23,24,25,26,27,29,30,31,32,33,34,35,36,37,39,40,41,43,44,45,46,47,48,51,52,53,54,55,57,58,59,60,61,62,65,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64,63,49,2,17,56,38,42,28,50,15,9] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [31]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([11], 29223.1338086734)

In [32]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,3,5,6,7,8,10,12,13,14,16,18,19,20,21,22,23,24,25,26,27,29,30,31,32,33,34,35,36,37,39,40,41,43,44,45,46,47,48,51,52,53,54,55,57,58,59,60,61,62,65,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64,63,49,2,17,56,38,42,28,50,15,9,11] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [33]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([6], 29213.509579401158)

In [34]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,3,5,7,8,10,12,13,14,16,18,19,20,21,22,23,24,25,26,27,29,30,31,32,33,34,35,36,37,39,40,41,43,44,45,46,47,48,51,52,53,54,55,57,58,59,60,61,62,65,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64,63,49,2,17,56,38,42,28,50,15,9,11,6] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [35]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([58], 29209.738625727012)

In [36]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,3,5,7,8,10,12,13,14,16,18,19,20,21,22,23,24,25,26,27,29,30,31,32,33,34,35,36,37,39,40,41,43,44,45,46,47,48,51,52,53,54,55,57,59,60,61,62,65,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64,63,49,2,17,56,38,42,28,50,15,9,11,6,58] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [37]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([65], 29206.22924955847)

In [38]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,3,5,7,8,10,12,13,14,16,18,19,20,21,22,23,24,25,26,27,29,30,31,32,33,34,35,36,37,39,40,41,43,44,45,46,47,48,51,52,53,54,55,57,59,60,61,62,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64,63,49,2,17,56,38,42,28,50,15,9,11,6,58,65] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [39]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([8], 29204.621835862177)

In [40]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,3,5,7,10,12,13,14,16,18,19,20,21,22,23,24,25,26,27,29,30,31,32,33,34,35,36,37,39,40,41,43,44,45,46,47,48,51,52,53,54,55,57,59,60,61,62,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64,63,49,2,17,56,38,42,28,50,15,9,11,6,58,65,8] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [41]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([27], 29203.19326540676)

In [42]:
metric_store = [[],[]]
for i, combination in enumerate(combinations([0,1,3,5,7,10,12,13,14,16,18,19,20,21,22,23,24,25,26,29,30,31,32,33,34,35,36,37,39,40,41,43,44,45,46,47,48,51,52,53,54,55,57,59,60,61,62,66],1), 1):
    x_data = sm.add_constant(df.iloc[:,[64,63,49,2,17,56,38,42,28,50,15,9,11,6,58,65,8,27] + list(combination)])
    mod  = sm.OLS(df.V202110x, x_data).fit()
    metric_store[0].append(list(combination))
    metric_store[1].append(mod.bic)

In [43]:
metric_store[0][np.argmin(metric_store[1])], np.min(metric_store[1])

([13], 29203.19326540676)

[64,63,49,2,17,56,38,42,28,50,15,9,11,6,58,65,8,27]

In [6]:
dfNew = df.iloc[:,[4,64,63,49,2,17,56,38,42,28,50,15,9,11,6,58,65,8,27]]

In [45]:
dfNew.head()

V202110x  V201103  V201100  V201241  V201008  V201601  V201216  V201416  \
0        -1        2        1        5        1        1        1        3   
1         3        5        2        3        1        1        1        1   
2         1        1        1        1        1        1        1        1   
3         1        1        2        3        1        1        2        1   
4         2        2        1        5        1        1        1        2   

   V201377  V201511x  V201240  V201602  V201627  V201622  V201651  V201157  \
0        1         4        5        1        1        1        1       85   
1        1         3        3        1        2        5        3       50   
2        3         2        1        3        3        2        3        0   
3        4         3        3        1        4        4        1       70   
4        2         5        4        1        4        1        2       70   

   V201036  V201628  V201515  
0       -1        3       -1  
1       -1        0        2  
2       -1        0       -1  
3       -1        0       -1  
4       -1        0       -1

In [ ]:
dfNew

In [46]:
dfNew = dfNew.rename(columns = {'V202110x': 'VFor','V201103': 'VFor2016' , 'V201100': 'Likely2V', 'V201241':'PBetterImmigration', 'V201008':'R2V', 'V201601':'SexualOrientation', 'V201216':'CareWhoWins', 'V201416':'GayMarriage', 'V201377':'TrustMedia', 'V201511x':'LevelOfEducation', 'V201240':'PBetterHealthcare', 'V201602':'JustifiedPViolence', 'V201627':'SelfCensor', 'V201622':'ConcernedPay4Healthcare', 'V201651':'SatisfiedWLife', 'V201157':'FThermometerR', 'V201036':'CandidatePref', 'V201628':'GunsOwned', 'V201515':'DiplomaOrGED'})

In [47]:
dfNew.head()

VFor  VFor2016  Likely2V  PBetterImmigration  R2V  SexualOrientation  \
0    -1         2         1                   5    1                  1   
1     3         5         2                   3    1                  1   
2     1         1         1                   1    1                  1   
3     1         1         2                   3    1                  1   
4     2         2         1                   5    1                  1   

   CareWhoWins  GayMarriage  TrustMedia  LevelOfEducation  PBetterHealthcare  \
0            1            3           1                 4                  5   
1            1            1           1                 3                  3   
2            1            1           3                 2                  1   
3            2            1           4                 3                  3   
4            1            2           2                 5                  4   

   JustifiedPViolence  SelfCensor  ConcernedPay4Healthcare  SatisfiedWLife  \
0                   1           1                        1               1   
1                   1           2                        5               3   
2                   3           3                        2               3   
3                   1           4                        4               1   
4                   1           4                        1               2   

   FThermometerR  CandidatePref  GunsOwned  DiplomaOrGED  
0             85             -1          3            -1  
1             50             -1          0             2  
2              0             -1          0            -1  
3             70             -1          0            -1  
4             70             -1          0            -1

In [ ]:
mod = smf.ols(formula='VFor ~ 1 + VFor2016 + Likely2V + PBetterImmigration + R2V + SexualOrientation + CareWhoWins + GayMarriage + TrustMedia + LevelOfEducation + PBetterHealthcare + JustifiedPViolence + SelfCensor + ConcernedPay4Healthcare + SatisfiedWLife + FThermometerR + CandidatePref + GunsOwned + DiplomaOrGED', data = dfNew)
res = mod.fit()
res.summary()

In [ ]:
plt.figure(dpi=150)
parties = ['D', 'R']
colors = {'-9':'blue', '-8':'red', '-1':'green', '1':'blue', '2':'red', '4':'red', '5':'blue'}
plt.scatter(df['V201029'], df['V201029'])

plt.xlim(0,100)
plt.ylim(0,100)
plt.legend(df['V201231x'].values)
plt.show()

In [ ]:
print("Test update")

In [7]:
dfNew['V202110x'].value_counts()

 1    3537
 2    2582
-1    1920
-9      81
 3      74
 5      60
 4      24
-8       2
Name: V202110x, dtype: int64

In [ ]:
loocv = LeaveOneOut()
regr = skl_lm.LinearRegression()
M = 16
pred = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
loocv_mse = []

for i in range(M):
    predMSE = []
    for j in pred:
        x_poly = PolynomialFeatures(i).fit_transform(dfNew.iloc[:,j].to_numpy().reshape(-1,1))
        mse = cross_val_score(regr, x_poly, dfNew.V202110x, cv=loocv, scoring='neg_mean_squared_error').mean()
        predMSE.append(-mse)
    val = 0
    for j in predMSE:
        val += j
    loocv_mse.append(val)

In [ ]:
loocv_mse

In [ ]:
from numpy import mean
from numpy import std
my_preds = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
X = dfNew.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]]
loocv = LeaveOneOut()
regr = skl_lm.LinearRegression()
scores = cross_val_score(regr, dfNew.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]], dfNew['VFor'], scoring='neg_mean_squared_error', cv=loocv, n_jobs=-1)
print('Accuracy: %.3f (%.3f)' % (mean(-scores), std(scores)))

In [ ]:
mod = skl_lm.LinearRegression()
Y_pred = mod.fit(dfNew.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]], dfNew['VFor']).predict(dfNew.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]])
Y_pred[0]

In [48]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
training_data, testing_data = train_test_split(dfNew, test_size=0.1, random_state=8)

In [51]:
x = dfNew.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]]
y = dfNew.iloc[:,[0]]

In [52]:
X_t, X_test, Y_t, Y_test = train_test_split(x, y, test_size=0.1)

In [69]:
clf = skl_lm.LogisticRegression(solver='lbfgs')
mod = clf.fit(X_t, Y_t)
print("Test Error = ", (1 - mod.score(X_t, Y_t)) * 100, "%")

C:\Users\JP\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


Test Error =  23.040794417606016 %


C:\Users\JP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [68]:
clf2 = GaussianNB()
mod2 = clf.fit(X_t, Y_t)
print("Test Error = ", (1 - mod2.score(X_t, Y_t)) * 100, "%")

C:\Users\JP\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


Test Error =  23.040794417606016 %


C:\Users\JP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [61]:
print(clf.predict([[X_test]])

SyntaxError: unexpected EOF while parsing (<ipython-input-61-344c619431f2>, line 1)

In [70]:
clf.fit(X_t, Y_t)
clf.predict(X_test)

C:\Users\JP\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\JP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([ 1, -1,  1, -1, -1,  1,  1,  1,  1,  2,  1,  2,  2,  2,  1,  1,  1,
        1,  2,  1,  2,  2, -1,  1,  2,  1,  1,  2,  2,  1,  2, -1,  2,  1,
       -1,  2,  2,  1,  2,  1,  1,  1,  1, -1,  1,  2,  2,  1,  1, -1, -1,
        2,  2,  2,  2,  2, -1,  2,  1,  2, -1,  1,  2,  1,  2,  1,  1,  1,
        1,  2, -1,  2,  2,  1,  1,  1,  2,  2,  1,  2,  1,  2,  1,  2,  1,
        2, -1, -1, -1,  2, -1,  2,  1,  2, -1, -1,  1,  1, -1,  1,  1,  2,
        1,  1,  1,  1,  1,  1,  1, -1,  2,  1,  1,  1,  1,  1,  2,  1,  1,
       -1,  2, -1,  1,  2,  2,  1,  2,  2,  1,  1,  2,  1,  1,  1,  1,  1,
        1, -1,  1,  2,  1,  1, -1, -1,  2,  1,  1,  1, -1,  2,  2,  1,  1,
       -1,  1,  1,  1,  1,  2,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,
        1,  1,  1, -1, -1,  2, -1,  1,  1,  2, -1,  2, -1,  2,  1,  1,  2,
        2, -1,  2,  1, -1,  2,  2,  2,  1, -1,  2,  2,  1,  1, -1,  1,  1,
        1,  2,  1, -1, -1,  1,  2,  2,  2,  2,  1,  2,  2,  1,  2,  1,  1,
        1,  1,  1, -1,  2

In [64]:
preds = clf.predict(X_test)

In [67]:
print(preds)

[ 1 -1  1 -1 -1  1  1  1  1  2  1  2  2  2  1  1  1  1  2  1  2  2 -1  1
  2  1  1  2  2  1  2 -1  2  1 -1  2  2  1  2  1  1  1  1 -1  1  2  2  1
  1 -1 -1  2  2  2  2  2 -1  2  1  2 -1  1  2  1  2  1  1  1  1  2 -1  2
  2  1  1  1  2  2  1  2  1  2  1  2  1  2 -1 -1 -1  2 -1  2  1  2 -1 -1
  1  1 -1  1  1  2  1  1  1  1  1  1  1 -1  2  1  1  1  1  1  2  1  1 -1
  2 -1  1  2  2  1  2  2  1  1  2  1  1  1  1  1  1 -1  1  2  1  1 -1 -1
  2  1  1  1 -1  2  2  1  1 -1  1  1  1  1  2  2  1  1  1  1  1  1  1  1
  1  2  1  1  1 -1 -1  2 -1  1  1  2 -1  2 -1  2  1  1  2  2 -1  2  1 -1
  2  2  2  1 -1  2  2  1  1 -1  1  1  1  2  1 -1 -1  1  2  2  2  2  1  2
  2  1  2  1  1  1  1  1 -1  2  1  1  1  1 -1  1  1 -1  1  1  2  2 -1  1
  1 -1  1 -1 -1 -1 -1  2  1  1  1  1  2  1  1  1 -1  2  1  2  1 -1  1  2
  1  2  1  2  1  2  2  1  2  2  2  2  1  1  2  1  2  2  1  2  1  2 -1 -1
  2  2  1  1  1  1  2  1  1  2 -1  1  1  2  2  1  1 -1 -1  1  1  2 -1 -1
  1  1  2  1 -1  2  1  1  1  1 -1 -1  1  1  2  1  1

In [65]:
score = clf.score(X_test, Y_test)
print(score)

0.751207729468599


In [66]:
from sklearn import metrics
cm = metrics.confusion_matrix(Y_test, preds)
print(cm)

[[  0   2   2   4   0   0]
 [  0  95  49  49   0   0]
 [  0  28 301  18   0   0]
 [  0  23  16 226   0   0]
 [  0   1   4   1   0   0]
 [  0   2   5   2   0   0]]
